### ISSUE TITLE
SHOWS just a BLANK page

### ISSUE THREAD

**Issue by abhinav2712** [orifmilod/iCinema#22]
After I did npm run dev into the root, It didnt display anything on my localhost:3000,  Do i have to download anything else execpt npm run setup??
Please clarify this issue,thanks

**Comment by orifmilod** [comment]
Hey, I have also noticed this issue, I think it's due to packages and Node JS versions being out of date, more specifically something with Webpack. I haven't been able to make time for fixing the issue, although would gladly accept any PR!

**Comment by orifmilod** [comment]
The issue was fixed in context of this PR: https://github.com/orifmilod/iCinema/pull/24
