### ISSUE TITLE
Inverted title box visible on the cards when the 'Summary' line is obscured by the navbar

### ISSUE THREAD

**Issue by k-piekarczyk** [orifmilod/iCinema#6]
If you turn the cards to see a movie's description and then scroll down, in a way that the navbar obscures the 'Summary' header on the card, the titlebox with inverted text is visible.

![A screenshot of the bug](https://user-images.githubusercontent.com/25866825/100720161-e6dcd600-33bd-11eb-9d28-4773b236cb68.png)

**Comment by orifmilod** [comment]
@k-piekarczyk oh I see. I'll fix that. Thanks a lot :)
