### ISSUE TITLE
The project is failing to load on the hosted heroku link

### ISSUE THREAD

**Issue by bikkimahato** [orifmilod/iCinema#7]
The project is failing to load on the hosted [heroku link](https://icinema1.herokuapp.com/movies)
![image](https://user-images.githubusercontent.com/42492682/132739717-8b2a2729-f9f3-4d79-8c8c-6159e89456b3.png)

**Comment by orifmilod** [comment]
Thanks for raising this, it was related to some missing data in the DB, fixed now :)
